### ISSUE TITLE
error push raw wns 

### ISSUE THREAD

**Issue by tienn2t** [gregberge/push-notify#10]
Hi all, 
i want to send push windowsphone with raw type
`service.send({
        channelURI: tokens,
        payload: '{"type":1,"data":8001,"parent_id":1,"message":"content push","title":"push title"}',
        type: 'raw'
    });`

but error: 
`err { [Error: One or more headers were specified incorrectly or conflict with another header.]
  headers: 
   { 'content-length': '0',
     'x-wns-notificationstatus': 'dropped',
     'x-wns-status': 'dropped',
     'x-wns-error-description': 'Content-Type should be application/octet-stream',
     'x-wns-msg-id': '39B8387B38F1E69E',
     'x-wns-debug-trace': 'HK2SCH130011845',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     date: 'Mon, 15 Aug 2016 08:17:24 GMT' },
  statusCode: 400,
  newAccessToken: 'EgCfAQMAAAAEgAAADAABJKui8Fdw8hyRn1VVH7VCU7gLVEIv7jz68f7GC/I1rPACnhE58/VdJnZa5mb1pbNQpc+LIawfRHvX6LNTT+YWbZ3PKJfxaQkxMX2ItQCwFb7NTYx/Bj1X3INhr9HTCTjeYmcdt7tfJ2F2XcJsTfUSzXZ1o0SM7dFku30nnlV9b2H/DG7aza6qJDUdQDfZFnGfkuonIsdNl3mYtHO5OqPfcalmf2pxl8Nbgm1Ko/VixNRmLPY2fp3ofK0zVevZdhBCWr9Tn6NPgBVNnzTRcqiqlMvMJvKqrpHt8Htrro/FnHztgw6eVtwplotoqa3dCx48RePssEGF2yjwyI/MycxINY4AWgCOAAAAAAAjtRdIlXqxV5V6sVfrSAQADwAxMTguNzAuMTkwLjExMgAAAAAAXwBtcy1hcHA6Ly9zLTEtMTUtMi0xMjA5NTE4MDE4LTExMzA1Mjc5ODQtMTgxMDc4NDkyNy0zNDE4NzExNzMxLTQxNjA2NjYwMzMtMjUwMTg2MDE3OS0xODI2OTc4MDY3AA==' }
`

how to fix it??

**Comment by gregberge** [comment]
@tienn2t I am sorry but I no longer use this plugin, I can't help you.
