### ISSUE TITLE
feedback service setup

### ISSUE THREAD

**Issue by pateljatin** [gregberge/push-notify#5]
Hi,

Is there a connection example on how to use existing connection and setup feedback service as per apn documentation? - https://github.com/argon/node-apn/blob/master/doc/feedback.markdown

If you can provide an example with push-notify - that would help a lot.

Cheers!

**Comment by gregberge** [comment]
@pateljatin there is no example with push-notify, you must use the apn module directly. push-notify provides only a unified API for the sending process but not for feedback that is specific to each services.

**Comment by pateljatin** [comment]
Thx @neoziro - appreciate it.
