### ISSUE TITLE
production push - Readme notes

### ISSUE THREAD

**Issue by pateljatin** [gregberge/push-notify#6]
Hi,

It would be great for others if we add a note in documentation to switch between production and sandbox environments...

```
{ production: true }
// set this to true when you are using production push gateway
// so define as:
var apn = notify.apn({
    key: config.prodkey,
    cert: config.prodcert,
    production: true
});
```

Let me know and I can do a pull request for you.

Cheers!
jatin

**Comment by gregberge** [comment]
@pateljatin feel free to PR yes :), but don't be to redundant with node-apn documentation, you can just put a link to it.
