### ISSUE TITLE
GCM notification repeating

### ISSUE THREAD

**Issue by ghost** [gregberge/push-notify#7]
hello, when I send notification to user device then it comes around number of time in which that user has number of devices.
means if a user has 4 devices { 4 gcm_ids }.
notification is send to all of them but in my case all of devices receiving notification but 4 time receiving.

var gcm = require('push-notify').gcm({
                    apiKey: gcm_apiKey,
            retries: 0
        });

gcm.send({
               registrationId: result[i]['device_id'],
             data: result[0]
          });

**Comment by gregberge** [comment]
I don't understand your problem

**Comment by ghost** [comment]
in simple ways, if a user is logged in 4 different devices. if gcm notification is sent to that user. so in this case if out of 4 devices 2 devices are offline.  and remaining 2 device getting 2-2 notification as that time ( same notification ).

**Comment by jpidelatorre** [comment]
I think that is a problem in your code. Can you provide the code you are using to make the calls?

**Comment by ghost** [comment]
here is my piece of code.

please refer this for my code:
https://jsfiddle.net/manprajapat/j16e6wya/
